image: node:latest

install-job:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deploy-prod:
  stage: deploy
  script:
    - CI=false npm run build
    - echo "-- build completed succesfully"
  dependencies:
    - install-job
  only:
    - main
